const fs = require('fs');
const path = require('path');
const marked = require('marked');
const hljs = require('highlight.js');
const glob = require('glob');

// Configure marked
marked.setOptions({
  highlight: function(code, lang) {
    const language = hljs.getLanguage(lang) ? lang : 'plaintext';
    return hljs.highlight(code, { language }).value;
  },
  breaks: true,
  gfm: true
});

// Read default CSS
const defaultCssPath = path.join(__dirname, '../public/styles/default.css');
const defaultCss = fs.readFileSync(defaultCssPath, 'utf8');

/**
 * Convert a single Markdown file to HTML
 * @param {string} mdPath - Path to Markdown file
 * @param {string} outputDir - Output directory
 * @param {string|null} customCssPath - Path to custom CSS file
 */
function convertFile(mdPath, outputDir, customCssPath = null) {
  try {
    // Read Markdown content
    const mdContent = fs.readFileSync(mdPath, 'utf8');

    // Convert to HTML
    const htmlContent = marked.parse(mdContent);

    // Get CSS
    let css = defaultCss;
    if (customCssPath && fs.existsSync(customCssPath)) {
      css += fs.readFileSync(customCssPath, 'utf8');
    }

    // Create HTML template
    const htmlTemplate = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${path.basename(mdPath, '.md')}</title>
    <style>${css}</style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>${path.basename(mdPath, '.md')}</h1>
            <p class="meta">Generated by md2html-cli</p>
        </header>
        <main class="content">
            ${htmlContent}
        </main>
        <footer class="footer">
            <p>&copy; 2025 md2html-cli</p>
        </footer>
    </div>
</body>
</html>`;

    // Write HTML file
    const htmlFileName = path.basename(mdPath, '.md') + '.html';
    const htmlPath = path.join(outputDir, htmlFileName);
    fs.writeFileSync(htmlPath, htmlTemplate);

    console.log(`✓ Converted: ${path.relative(process.cwd(), mdPath)} -> ${path.relative(process.cwd(), htmlPath)}`);
  } catch (error) {
    console.error(`✗ Error converting ${mdPath}:`, error.message);
  }
}

/**
 * Convert all Markdown files in a directory
 * @param {string} dirPath - Path to directory
 * @param {string} outputDir - Output directory
 * @param {string|null} customCssPath - Path to custom CSS file
 */
function convertDirectory(dirPath, outputDir, customCssPath = null) {
  // Find all .md files recursively
  const mdFiles = glob.sync(path.join(dirPath, '**', '*.md'));

  if (mdFiles.length === 0) {
    console.log(`No Markdown files found in ${dirPath}`);
    return;
  }

  mdFiles.forEach(mdFile => {
    convertFile(mdFile, outputDir, customCssPath);
  });
}

/**
 * Convert Markdown file or directory to HTML
 * @param {string} sourcePath - Path to source file or directory
 * @param {string} outputDir - Output directory
 * @param {string|null} customCssPath - Path to custom CSS file
 */
function convert(sourcePath, outputDir, customCssPath = null) {
  const stats = fs.statSync(sourcePath);

  if (stats.isFile() && path.extname(sourcePath) === '.md') {
    convertFile(sourcePath, outputDir, customCssPath);
  } else if (stats.isDirectory()) {
    convertDirectory(sourcePath, outputDir, customCssPath);
  } else {
    console.error(`Error: "${sourcePath}" is not a Markdown file or directory.`);
  }
}

module.exports = {
  convert,
  convertFile,
  convertDirectory
};
