CREATE TABLE IF NOT EXISTS 快递 (
  id SERIAL PRIMARY KEY,
  单号 VARCHAR(50) UNIQUE NOT NULL,
  快递公司 VARCHAR(50),
  当前状态 VARCHAR(50) DEFAULT '待处理',
  物流信息 JSONB,
  异常状态 BOOLEAN DEFAULT FALSE,
  创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  更新时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_快递_单号 ON 快递 (单号);
CREATE INDEX IF NOT EXISTS idx_快递_当前状态 ON 快递 (当前状态);
CREATE INDEX IF NOT EXISTS idx_快递_更新时间 ON 快递 (更新时间);
